### ISSUE TITLE
Debugging the webview

### ISSUE THREAD

**Issue by j0weiss** [WPO-Foundation/iWptBrowser#1]
You wrote [here](https://github.com/WPO-Foundation/wptagent/issues/25#issuecomment-326683679) that the embedded webview is debuggable from within Safari. Unfortunately I wasn't able to recreate this behaviour. In the developer menu of Safari I only get the message `No Inspectable Application` under the device where I deployed the app. Did I miss something how I have to deploy the app?

Thanks for your help!

**Comment by pmeenan** [comment]
Some quick notes:
* Settings -> Safari -> Advanced (on the phone): make sure "Web Inspector" is enabled
* Make sure the phone is attached to the development account that you are using to build (make sure the build has the correct team set)
* When you deploy the app, you need to deploy it "for development"
    * It can be a release build or debug build
    * If you run it on the device from within XCode (at least once) it will automatically deploy a debug build that you can then launch manually.  Otherwise, if you do an archive build and export from the archive, make sure you export it "for development"

You may have done all of that right already, the app itself starts without a browser session.  You need to connect to the app and launch a browser.

For initial testing I use [tcprelay](https://github.com/rcg4u/iphonessh/tree/master/python-client) and run:

```
python tcprelay.py 19222
```

That forwards port 19222 on the mac to the app which listens on 19222.  Then you can telnet to localhost and control the app over telnet.  The commands are one per line and tab-delimited.  Some useful commands:

* clearcache
* startbrowser
* navigate<tab>http://www.example.com
* exec<tab>some javascript code to run;
* closebrowser

Once you have a browser open with "startbrowser" you should be able to connect to it.

You can also modify the app to automatically start a browser when it launches but in actual testing it is useful to be able to start/kill the browser on command and to set up portrait/landscape, clear cache, etc before launching it.

**Comment by j0weiss** [comment]
Works like a charm, thank you very much!
I missed the part where I have to forward the port.
